version: "3.5"
services:
  beacon-chain:
    build:
      context: ./beacon-chain
      args:
        BEACON_API_PORT: 3500
        UPSTREAM_VERSION: 22.8.1
    environment:
      BEACON_API_PORT: 3500
      HTTP_ENGINE: "http://goerli-geth.dappnode:8551"
      P2P_PORT: 9505
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
    volumes:
      - "teku-prater-data:/opt/teku/data"
    ports:
      - "9505:9505/tcp"
      - "9505:9505/udp"
    restart: unless-stopped
    image: "beacon-chain.teku-prater.dnp.dappnode.eth:0.1.0"
  validator:
    build:
      context: ./validator
      args:
        UPSTREAM_VERSION: 22.8.1
    environment:
      LOG_TYPE: INFO
      BEACON_NODE_ADDR: "http://beacon-chain.teku-prater.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
    restart: unless-stopped
    image: "validator.teku-prater.dnp.dappnode.eth:0.1.0"
volumes:
  teku-prater-data: {}
